# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b2f4916f9067a73ae89cf3ea1be467d3211b2d59103f5cbeff85bd668fd7c194da219d6c7a1946eba56f9efb9f3671d4a9923ee10879a9fa03a3349c73c2c95

test:
  secret_key_base: af8d6d1d1c034345336cca2c94ab0474fd99ecc416ee3fead327a0e91a287f9b1531251d6496a9b2ed0e516183e4052dc691f49a6c95a5426639761c983cf155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
